
-- =======================================
-- Tabla: FX_TRADE_SIGNATURE
-- =======================================
CREATE TABLE ACELER_FX.FX_TRADE_SIGNATURE (
    TRADE_SIGNATURE_ID NUMBER(38,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    ENTITY             VARCHAR2(4 CHAR) NOT NULL,
    ORIGIN_ID          NUMBER(22,0) NOT NULL,
    ORIGIN             VARCHAR2(20 CHAR) NOT NULL,
    PRODUCT_ID         VARCHAR2(2 CHAR) NOT NULL,
    SIGNATURE_TYPE     VARCHAR2(10 CHAR) NOT NULL,
    INDICATOR_SSCC     VARCHAR2(1 CHAR),
    VALIDATED_BO       VARCHAR2(10 CHAR),
    EXPEDIENT_ID       NUMBER(22,0),
    FECALTA            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUALTA            VARCHAR2(30 CHAR) NOT NULL,
    FECMODI            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUMODI            VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT PK_FX_TRADE_SIGNATURE PRIMARY KEY (TRADE_SIGNATURE_ID)
) TABLESPACE ACELER_FX_DATOS;

COMMENT ON TABLE ACELER_FX.FX_TRADE_SIGNATURE IS 'Table storing FX trade or event signature data.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.TRADE_SIGNATURE_ID IS 'TRADE SIGNATURE CODE';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.ENTITY IS 'ENTIDAD CODE.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.ORIGIN_ID IS 'TRADE ID OR EVENT ID CODE.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.ORIGIN IS 'Indicates whether its a trade or an event.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.PRODUCT_ID IS 'Product id code.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.SIGNATURE_TYPE IS 'Signature Type Code. PAPER / DIGITAL.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.INDICATOR_SSCC IS 'Indicates if the product is sent to Partenon SSCC, only applicable for derivatives.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.VALIDATED_BO IS 'VALIDATED BO STATUS: PENDING, OK, KO.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.EXPEDIENT_ID IS 'ID EXPEDIENT CODE.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.FECALTA IS 'Trade signature registration date.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.USUALTA IS 'Trade signature registration user.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.FECMODI IS 'Trade signature modification date.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNATURE.USUMODI IS 'Trade signature modification user.';

GRANT SELECT, INSERT, UPDATE, DELETE ON ACELER_FX.FX_TRADE_SIGNATURE TO ACELER_APL;

-- =======================================
-- Tabla: FX_TRADE_SIGNER
-- =======================================
CREATE TABLE ACELER_FX.FX_TRADE_SIGNER (
    TRADE_SIGNER_ID    NUMBER(22) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TRADE_SIGNATURE_ID NUMBER(22) NOT NULL,
    DOCUMENT_TYPE      VARCHAR2(1 CHAR) NOT NULL,
    DOCUMENT_NUMBER    VARCHAR2(20 CHAR) NOT NULL,
    SIGNER_ID          VARCHAR2(10 CHAR) NOT NULL,
    NAME               VARCHAR2(200 CHAR) NOT NULL,
    IS_CLIENT          VARCHAR2(1 CHAR) NOT NULL,
    INTERVENTION_TYPE  VARCHAR2(2 CHAR) NOT NULL,
    FECALTA            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUALTA            VARCHAR2(30 CHAR) NOT NULL,
    FECMODI            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUMODI            VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT PK_FX_TRADE_SIGNER PRIMARY KEY (TRADE_SIGNER_ID),
    CONSTRAINT FK_TRADE_SIGNER_SIGNATURE FOREIGN KEY (TRADE_SIGNATURE_ID)
        REFERENCES ACELER_FX.FX_TRADE_SIGNATURE (TRADE_SIGNATURE_ID)
) TABLESPACE ACELER_FX_DATOS;

COMMENT ON TABLE ACELER_FX.FX_TRADE_SIGNER IS 'Trade signer details for FX operations.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.TRADE_SIGNER_ID IS 'Signer ID.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.TRADE_SIGNATURE_ID IS 'Trade signature code.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.DOCUMENT_TYPE IS 'Document type signer code.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.DOCUMENT_NUMBER IS 'Document signer code.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.SIGNER_ID IS 'Person signer type and code.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.NAME IS 'Signer name.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.IS_CLIENT IS 'Is client code.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.INTERVENTION_TYPE IS 'Intervention type code.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.FECALTA IS 'Signer registration date.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.USUALTA IS 'Signer registration user.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.FECMODI IS 'Signer modification date.';
COMMENT ON COLUMN ACELER_FX.FX_TRADE_SIGNER.USUMODI IS 'Signer modification user.';

GRANT SELECT, INSERT, UPDATE, DELETE ON ACELER_FX.FX_TRADE_SIGNER TO ACELER_APL;

-- =======================================
-- vista: FX_VIEW_TRADE_SIGNATURE_EXPEDIENT
-- =======================================
CREATE OR REPLACE EDITIONABLE VIEW ACELER_FX.FX_VIEW_TRADE_SIGNATURE_EXPEDIENT AS
SELECT
    TS.TRADE_SIGNATURE_ID,
    TS.ENTITY,
    TS.ORIGIN_ID,
    TS.PRODUCT_ID,
    TS.SIGNATURE_TYPE,
    TS.VALIDATED_BO,
    TS.INDICATOR_SSCC,
    TS.EXPEDIENT_ID,
    DE.START_DATE,
    DE.END_DATE,
    DE.STATUS AS EXPEDIENT_STATUS
FROM ACELER_FX.FX_TRADE_SIGNATURE TS
         LEFT JOIN ACELER_DFD.DFD_EXPEDIENT DE
                   ON TS.EXPEDIENT_ID = DE.ID_EXP_SEC;

-- =======================================
-- vista: FX_VIEW_TRADE_SIGNER_DOCUMENT_STATUS
-- =======================================
CREATE OR REPLACE EDITIONABLE VIEW ACELER_FX.FX_VIEW_TRADE_SIGNER_DOCUMENT_STATUS AS
SELECT
    TS.TRADE_SIGNATURE_ID,
    TS.EXPEDIENT_ID,
    SG.SIGNER_ID,
    SG.DOCUMENT_TYPE,
    SG.DOCUMENT_NUMBER,
    SG.NAME,
    SG.IS_CLIENT,
    SG.INTERVENTION_TYPE,
    DD.GN_ID,
    DD.TYPE_DOC AS DOCUMENTAL_TYPE_DOC,
    DD.INDICATOR_PRECONTRACTUAL,
    DS.SIGNED_DOC,
    DS.SIGN_DATE
FROM ACELER_FX.FX_TRADE_SIGNATURE TS
         LEFT JOIN ACELER_FX.FX_TRADE_SIGNER SG
                   ON TS.TRADE_SIGNATURE_ID = SG.TRADE_SIGNATURE_ID
         LEFT JOIN ACELER_DFD.DFD_EXPEDIENT DE
                   ON TS.EXPEDIENT_ID = DE.ID_EXP_SEC
         JOIN ACELER_DFD.DFD_EXPEDIENT_DOCUMENT DED
              ON DED.EXPEDIENT_ID = DE.ID
         JOIN ACELER_DFD.DFD_DOCUMENT DD
              ON DED.DOCUMENT_ID = DD.ID
         JOIN ACELER_DFD.DFD_SIGNER DS
              ON DD.ID = DS.DOCUMENT_ID;

GRANT SELECT ON ACELER_FX.FX_VIEW_TRADE_SIGNATURE_EXPEDIENT TO ACELER_APL;
GRANT SELECT ON ACELER_FX.FX_VIEW_TRADE_SIGNER_DOCUMENT_STATUS TO ACELER_APL;