SET SERVEROUTPUT ON

SET VERIFY OFF
SET FEEDBACK OFF
SET HEAD OFF
SET TERMOUT OFF
SET FLUSH OFF
SET LINES 800
SET TRIMSPOOL ON


-- Genero el fichero
SPOOL TempFX_D.dat

DECLARE


PROCEDURE p_asesoramiento
IS    

  CURSOR CUR_ASES IS 

--FX
SELECT (TO_CHAR(SYSDATE, 'DD/MM/YYYY') -- AS "FECHA_PROCESO"
  ||';'
  || OP.ID_OPERACION -- AS "CODIGO_OPERACION"
  ||';'
  || 'ACE_'
  || LPAD ( OP.ID_OPERACION , 12 , '0' ) -- AS ID_OPERACION concatenado con ACE_+0 hasta 12 n�meros
  ||';'
  || '1999'
  || LPAD ( OP.ID_OPERACION , 6 , '0' ) -- AS "ID MX" 1999
  ||';'
  || NVL(DECODE (LENGTH(OP_FX.CONTRATO_PARTENON),20,SUBSTR(OP_FX.CONTRATO_PARTENON,1,8)
  || SUBSTR(OP_FX.CONTRATO_PARTENON,11,10),OP_FX.CONTRATO_PARTENON),'')-- AS "CONTRATO PARTENON" Vac�o si es nulo
  ||';'
  || (SELECT DESCPRODUCTO FROM ACELER.ACE_PRODUCTO_OPER WHERE ID_PRODUCTO=OP.PRODUCTO AND IDIOMA = 'es') -- AS "PRODUCTO"
  ||';'
  || TO_CHAR (OP_FX.FECHA_OPERACION, 'DD/MM/YYYY HH24:MI:SS')||'.000000'-- AS "FECHA_CONTRATACION" 
  ||';'
  || TO_CHAR (OP_FX.FECHA_VENCIMIENTO_OPC1,'DD/MM/YYYY') -- AS "FECHA_VENCIMIENTO"
  ||';'
  || '' -- AS "FECHA_CANCELACION" No se env�a
  ||';'
  || OP_FX.DIVISA_NOMINAL_FW  -- AS "DIVISA OPERACI�N" 
  ||';'
  || SUBSTR(OP_FX.PAR_DIVISAS_FW,1,3) || SUBSTR(OP_FX.PAR_DIVISAS_FW,5,3) -- AS "PAR DE DIVISAS"
  ||';'
  || OP.NOMINAL -- AS "NOMINAL"
  ||';'
  ||'ACELERA FX' -- AS "SISTEMA ORIGEN"
  ||';'
  || DECODE ( OP_FX.SENTIDO , 'EXP' , 'C' , 'V' ) -- AS "SENTIDO" SABER CUAL ES EL MAPEO
  ||';'
  || NVL(PR.ID_PROPUESTA,'') -- AS "ID PROPUESTA"
  ||';'
  || DECODE(NVL(PR.ID_PROPUESTA,''),'','N','S') -- AS "INDICADOR ASESORAMIENTO" Si tiene propuestas se pone si
  ||';'
  || TST.RESUL_IDONIEDAD -- AS "RESULTADO IDONEIDAD"
  ||';'
  || 'N' -- AS "CAPITAL GARANTIZADO (S/N)" Para productos DISTINTOS A DEPOS = 'N'
  ||';'
  || '' -- AS "% GARANTIZADO" Para productos DISTINTOS A DEPOS vac�o
  ||';'
  || OP_FX.SEGMENTO_TIT -- AS "SEGMENTO COMERCIAL" Segmento de la contrapartida
  ||';'
  || '' -- AS "PRIMA" Vac�o para productos distintos a OPCIONES
  ||';'
  || TI.HOSTID -- AS "CONTRAPARTIDA (C�DIGO F/J)"
  ||';'
  || NVL(OP_FX.CONTRAPARTIDA_TIT,'') -- AS "C�DIGO GLCS" Si est� a NULL se deja
  -- vac�o
  ||';'
  || OP.IDCENT -- AS "OFICINA"
  ||';'
  || UPPER(NVL(OP.NUMGESTOR,OP.USUALTA)) -- AS "GESTOR/VENTAS" 
  ||';'
  || '' -- AS "COTITULARES" Vac�o
  ||';'
  || '' -- AS "EMISOR" Vac�o
  ||';'
  || '' -- AS "NIVEL_DE_RIESGO" Para FX vac�o
  ||';'
  || NVL(MF.INEXPE,'')
  || DECODE (MF.CDEXPEDI,0,'',LPAD(TO_CHAR(MF.CDEXPEDI),15,'0'))
  -- AS "CODIGO_MIFID" Tipo ejemplo: M000000021842382 (16)
  ||';'
  || '' -- AS "Orden SIGA" Parece que solo est� para SWAP
  ||';'
  || NVL(MF.CODFFVV,'') -- AS "CODIGO_FFVV" C�digo del Fichero de
  -- Valores
  ||';'
  || '' -- AS "SIN�NIMO SIGA" Parece que solo est� para SWAP
  ||';'
  || '1' -- AS "TIPO SUBYACENTE" Para FX 1
  ||';'
  || '' -- AS "C�DIGO SUBYACENTE" Vac�o
  ||';'
  || DECODE(LENGTH(NVL(OP_FX.CCC_PARTENON,'')),0,
            (DECODE(LENGTH(NVL(OP_FX.CCC,'')),0,'',
                DECODE(LENGTH(OP_FX.CCC),20,
                SUBSTR(OP_FX.CCC,1,8) || SUBSTR(OP_FX.CCC,11,10)),
                OP_FX.CCC)),
             DECODE(LENGTH(OP_FX.CCC_PARTENON),20,
                SUBSTR(OP_FX.CCC_PARTENON,1,8) || SUBSTR(OP_FX.CCC_PARTENON,11,10),
                OP_FX.CCC_PARTENON)
            )  -- AS "CUENTA CORRIENTE" Para el PFE y en Estructuras si se marca,
  ||';'
  || NVL(OP_FX.DIVISA_NOMINAL_FW,'') -- AS "DIVISA CUENTA CORRIENTE" Para el PFE y en Estructuras si se
  -- marca, resto vac�o 
  ||';'
  || '' -- AS "CUENTA CORRIENTE 2" Para el PFE y en Estructuras si se marca. En FX solo hay una CCC
  ||';'
  || '' -- AS "DIVISA CUENTA CORRIENTE 2" Para el PFE y en Estructuras si se marca. En FX solo hay una CCC
  ||';'
  || '' -- AS "CONTRATO MARCO" Para el PFE y en Estructuras si se
  -- marca. Solo est�n en SWAP
  ||';'
  || '' --AS "CCV" Vac�o para FX
  ||';'
  || RTRIM(TO_CHAR(ABS(NVL(SC.BENEFICIO, 0) + NVL(SC.VALOR_MERCADO_TOTAL, 0)) + NVL(SC.CVA, 0) + NVL(ABS(SC.CREDIT_SALES), 0) + DECODE(CLIENT_FAIR_VALUE_SCOPE, 'Y', NVL(ABS(SC.ADDON_AMOUNT), 0) , 0) , 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.''' ) , ',' )
  -- AS "COSTES GASTOS TOTALES"
  ||';'
  || SUBSTR(OP_FX.PAR_DIVISAS_OPC1,1,3)-- AS "DIVISA CyG" 
  ||';'
  || DECODE (OP.PRODUCTO,'SL','471','SF','471','SD','471','SE','471','SU','471','FW','441','FA','441','ND','440','SW','441','DW','471','SP','441') -- AS "TIPO PRODUCTO PTN" C�digo PARTEN�N
  ||';'
  || DECODE (OP.PRODUCTO,'SL','001','SF','001','SD','001','SE','001','SU','001','FW','001','FA','002','ND','040','SW','001','DW','001','SP','001') -- AS "SUBTIPO PRODUCTO PTN" C�digo PARTEN�N
  ||';'
  || MAX(NVL(DOC.ID_DOC_LPA ,'')) -- AS "ID DOC (KID)" ID_DOC_LPA si lo tenemos,
  -- sino vacio
  ||';'
  || MAX(NVL(DOC.ID_LPA ,'')) -- AS "WF ID KID" ID_LPA si lo tenemos, sino vacio
  ||';'
  ||'' -- AS "ISIN" Para FX vac�o
  ||';'
  || DECODE (OP.PRODUCTO,'SP','CURR;FXD;FXD',
                         'FW','CURR;FXD;FXD', 'FA','CURR;FXD;FXD', 
                         'SW','CURR;FXD;XSW', 'ND','CURR;FXD;FXD', 
                         'SL','CURR;OPT;BAR', 'SD','CURR;OPT;BAR', 
                         'SE','CURR;OPT;BAR', 'SU','CURR;OPT;BAR', 
                         'SF','CURR;OPT;RBT', 'DW','IRD;LN_BR;') -- AS MX_FAMILY, MX_GROUP, AS MX_TYPE
  ||';' 
  || 'S' -- AS "ESTRUCTURA" Son todas estructuras
  ||';'
  || (NVL(SC.BENEFICIO,0) + NVL(ABS(SC.CVA),0) + NVL(ABS(SC.CREDIT_SALES),0) )  -- AS "MARKUP"  Costes y gastos totales
  ||';'
  || MF.CODMIFID --AS ACCIONM
  ||';'
  || '' -- AS CAMPID
  ||';'
  || '' -- AS C�DIGO AAFF
  || ';'
  || DECODE (OP_FX.MIFID, 'S', 'N', 'S')  -- AS "MEDIO DE PAGO"
  ||';'
  ||  OP_FX.CLASF_MIFID_TIT -- AS "CLASIFICACION MIFID"
  ||';'
  || DECODE(OP.CANAL,'ACELERA','OFI','INT') -- AS "CANAL"
  ||';'
  ||'' -- AS TIPO_OBJETO_CUBIERTO
  ||';'
  ||'' -- AS CONTRATO_OBJETO_CUBIERTO
  ||';'
  ||OP.PRODUCTO -- AS "CODIGO_PRODUCTO"
  || ';'
  ||'' -- AS TIPO_EVENTO
  ||';'
  ||'' -- AS CONT_PARTENON_OP_PADRE
  ||';'
  ||'' -- AS MADRE_HIJA
  ||';'
  ||'' -- AS OPERACION_MADRE
  ||';'
  ||'' -- AS ORIGEN_CONTRAPARTIDA
  ||';'
  ||'' -- AS CONTR_BASICO_VALID
  ||';'
  ||'' -- AS CONTR_BASICO_STATUS
  ||';'
  ||'' -- AS CARTA_CLASIF_IND_FIRMA
  ||';'
  ||'' -- AS CARTA_CLASIF_TIPO_FIRMA
  ||';'
  ||'' -- AS LEI_NATIONALID_VALID
  ||';'
  ||'' -- AS LEI_NATIONALID_VALUE
  ||';'
  ||'' -- AS LEI_STATUS
  ||';'
  ||'' -- AS EMIR_STATUS_REFIT
  ||';'
  ||'' -- AS DFA_ACTION
  ||';'
  ||'' -- AS FIOC_VALID
  ||';'
  ||'' -- AS FIOC_STATUS
  ||';'
  ||'' -- AS NOMINAL_MAXIMO_COBERTURA
  ||';'
  ||'' -- AS T_MIFID_TIPO_TEST
  ||';'
   ||'' -- AS T_MIFID_INDVIGENCIA
  ||';'
  ||'' -- AS T_MIFID_ESTADO_TEST
  ||';'
  ||'' -- AS T_MIFID_FECHAFIN
  ||';'
  ||'' -- AS T_MIFID_RESULTIDON
  ||';'
  ||'' -- AS T_MIFID_RESULTCONVE
  ||';'
  ||'' -- AS T_MIFID_RESULTCOBER
  ||';'
  ||'' -- AS CAMP_ORG
  ||';'
  || RTRIM(TO_CHAR(NVL(SC.MID_PRICE , 0), 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.'''), ',' ) -- AS "MID_PRICE"
  || ';'
  || RTRIM(TO_CHAR(DECODE(OP_FX.CLIENT_FAIR_VALUE_SCOPE, 'Y', SC.ADDON_AMOUNT, 0), 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.''' ), ',')) -- AS "ADDON_PRICE"
  || ';'
  || OP.MIFID_ACT_TELEPHONE_CALL_RECORDED -- AS "MIFID_ACT_CALL_RECORDED"
  || ';'
  || OP.MIFID_ACT_ID -- AS "MIFID_ACT_ID"
  || '' AS DETALLE
FROM ACELER.ACE_OPERACION_FX OP_FX
INNER JOIN ACELER.ACE_OPERACION OP
ON OP_FX.ID_OPERACION = OP.ID_OPERACION AND OP_FX.ID_ENTIDAD = OP.ID_ENTIDAD
INNER JOIN ACELER.ACE_OPERACION_TITULARES TI
ON OP.ID_OPERACION      = TI.ID_OPERACION AND OP_FX.ID_ENTIDAD = TI.ID_ENTIDAD
AND TI.TIPO_TITULARIDAD = 'T'
LEFT OUTER JOIN ACELER.ACE_OPERACION_PRECIO_SSCC SC
ON OP.ID_OPERACION = SC.ID_OPERACION AND OP_FX.ID_ENTIDAD = SC.ID_ENTIDAD
LEFT OUTER JOIN ACELER.ACE_MIFID MF
ON OP_FX.ID_OPERACION = MF.ID_OPERACION AND OP_FX.ID_ENTIDAD = MF.ID_ENTIDAD
LEFT OUTER JOIN ACELER.ACE_DOCUMENTOS DOC
ON OP_FX.ID_OPERACION = DOC.ID_OPERACION
AND DOC.ID_TIPDOC     = 'KD' AND DOC.ID_ENTIDAD = OP_FX.ID_ENTIDAD
LEFT OUTER JOIN ACELER.ACE_PROPUESTAS_FX PR
ON PR.ID_OPERACION = OP_FX.ID_OPERACION AND PR.ID_ENTIDAD = OP_FX.ID_ENTIDAD
LEFT OUTER JOIN ACELER.ACE_TEST_CLIENTE TST
ON OP.TITULAR = TST.HOSTID AND TST.FECHA_VENCIMIENTO >= SYSDATE
--WHERE
WHERE OP.ID_ESTADO IN ('FM','KE','KF','OE','OF','FF','FE') AND
TO_DATE(OP_FX.FECHA_OPERACION,'DD/MM/YYYY') = TO_DATE(SYSDATE,'DD/MM/YYYY') 
GROUP BY OP.ID_OPERACION,OP_FX.CONTRATO_PARTENON, OP.PRODUCTO,OP_FX.FECHA_OPERACION,
OP_FX.FECHA_VENCIMIENTO_OPC1,OP_FX.PAR_DIVISAS_FW,
OP.NOMINAL,OP_FX.SENTIDO,PR.ID_PROPUESTA,TST.RESUL_IDONIEDAD,
OP_FX.SEGMENTO_TIT,SC.PRIMA,TI.HOSTID,OP_FX.CONTRAPARTIDA_TIT,
OP.IDCENT,OP.NUMGESTOR,OP.USUALTA,MF.INEXPE,MF.CDEXPEDI,MF.CODFFVV,
OP_FX.CCC,OP_FX.DIVISA_NOMINAL_FW,SC.BENEFICIO_PORCENTAJE,SC.VALOR_MERCADO_TOTAL,
OP_FX.NOMINAL_OPC1,OP_FX.CCC_PARTENON,SC.BENEFICIO,SC.CVA,SC.CREDIT_SALES, OP.CANAL,
OP_FX.CLASF_MIFID_TIT, OP_FX.MIFID, MF.CODMIFID, OP_FX.DIVISA_NOMINAL_FW,
SC.MID_PRICE, SC.ADDON_AMOUNT,OP_FX.PAR_DIVISAS_OPC1,OP_FX.CLIENT_FAIR_VALUE_SCOPE,
OP.MIFID_ACT_TELEPHONE_CALL_RECORDED, OP.MIFID_ACT_ID
UNION
--FWD
SELECT (TO_CHAR(SYSDATE, 'DD/MM/YYYY') -- AS "FECHA_PROCESO"
  ||';'
  || OP.ID_OPERACION -- AS "CODIGO_OPERACION"
  ||';'
  || DECODE ( OP_FWD.DESTINO , 'MX' , 'ACE_', '')
  || DECODE ( OP_FWD.DESTINO , 'MX' , LPAD ( OP.ID_OPERACION , 12 , '0' ) , '') -- AS ID_OPERACION concatenado con ACE_+0 hasta 12 n�meros
  ||';'
  || DECODE ( OP_FWD.DESTINO , 'MX' , '1999' , '')
  || DECODE ( OP_FWD.DESTINO , 'MX' , LPAD ( OP.ID_OPERACION , 6 , '0' ) , '')-- AS "ID MX" 1999
  ||';'
  || NVL(DECODE (LENGTH(OP_FWD.CONTRATO_PARTENON),20,SUBSTR(OP_FWD.CONTRATO_PARTENON,1,8)
       || SUBSTR(OP_FWD.CONTRATO_PARTENON,11,10),OP_FWD.CONTRATO_PARTENON),'') 
       || NVL(DECODE (LENGTH(OP_FWD.CONTRATO_PARTENON_SWAP),20,'#'||SUBSTR(OP_FWD.CONTRATO_PARTENON_SWAP,1,8)
       || SUBSTR(OP_FWD.CONTRATO_PARTENON_SWAP,11,10),DECODE(OP_FWD.CONTRATO_PARTENON_SWAP,NULL,'','#'||OP_FWD.CONTRATO_PARTENON_SWAP)),'') 
-- AS "CONTRATO PARTENON" Vac�o si es nulo
  ||';'
  || (SELECT DESCPRODUCTO FROM ACELER.ACE_PRODUCTO_OPER WHERE ID_PRODUCTO=OP.PRODUCTO AND IDIOMA = 'es') -- AS "PRODUCTO"
  ||';'
  || TO_CHAR (OP_FWD.FECHA_OPERACION, 'DD/MM/YYYY HH24:MI:SS')||'.000000'-- AS "FECHA_CONTRATACION" 
  ||';'
  || TO_CHAR (OP_FWD.FECHA_VENCIMIENTO,'DD/MM/YYYY') -- AS "FECHA_VENCIMIENTO"
  ||';'
  || '' -- AS "FECHA_CANCELACION" No se env�a
  ||';'
  || DECODE (OP_FWD.SENTIDO,'C',OP_FWD.DIVISA_NOMINAL_CC,OP_FWD.DIVISA_NOMINAL_CV)  -- AS "DIVISA OPERACI�N"
  ||';'
  || SUBSTR(OP_FWD.PAR_DIVISAS,1,3) || SUBSTR(OP_FWD.PAR_DIVISAS,5,3) -- AS "PAR DE DIVISAS"
  ||';'
  || OP.NOMINAL -- AS "NOMINAL"
  ||';'
  ||'ACELERA FX' -- AS "SISTEMA ORIGEN"
  ||';'
  || OP_FWD.SENTIDO -- AS "SENTIDO" SABER CUAL ES EL MAPEO
  ||';'
  || NVL(PR.ID_PROPUESTA,'') -- AS "ID PROPUESTA"
  ||';'
  || DECODE(NVL(PR.ID_PROPUESTA,''),'','N','S') -- AS "INDICADOR ASESORAMIENTO" Si tiene propuestas se pone si
  ||';'
  || TST.RESUL_IDONIEDAD -- AS "RESULTADO IDONEIDAD"
  ||';'
  ||'N'-- AS "CAPITAL GARANTIZADO (S/N)" Para productos DISTINTOS A DEPOS = 'N'
  ||';'
  ||'' --AS "% GARANTIZADO" Para productos DISTINTOS A DEPOS vac�o
  ||';'
  || OP_FWD.SEGMENTO_TIT -- AS "SEGMENTO COMERCIAL" Segmento de la contrapartida
  ||';'
  || 0 -- AS "PRIMA" Vac�o para productos distintos a OPCIONES
  ||';'
  || TI.HOSTID -- AS "CONTRAPARTIDA (C�DIGO F/J)"
  ||';'
  || NVL(OP_FWD.CONTRAPARTIDA_TIT,'') -- AS "C�DIGO GLCS" Si est� a NULL se deja
  -- vac�o
  ||';'
  || OP.IDCENT -- AS "OFICINA"
  ||';'
  || UPPER(NVL(OP.NUMGESTOR,OP.USUALTA)) -- AS "GESTOR/VENTAS" 
  ||';'
  || '' -- AS "COTITULARES" Vac�o
  ||';'
  || '' -- AS "EMISOR" Vac�o
  ||';'
  || '' -- AS "NIVEL_DE_RIESGO" Para FX vac�o
  ||';'
  || NVL(MF.INEXPE,'')
  || DECODE (MF.CDEXPEDI,0,'',LPAD(TO_CHAR(MF.CDEXPEDI),15,'0'))
  -- AS "CODIGO_MIFID" Tipo ejemplo: M000000021842382 (16)
  ||';'
  || '' -- AS "Orden SIGA" Parece que solo est� para SWAP
  ||';'
  || NVL(MF.CODFFVV,'') -- AS "CODIGO_FFVV" C�digo del Fichero de
  -- Valores
  ||';'
  || '' -- AS "SIN�NIMO SIGA" Parece que solo est� para SWAP
  ||';'
  || '1' -- AS "TIPO SUBYACENTE" Para FX 1
  ||';'
  || '' -- AS "C�DIGO SUBYACENTE" Vac�o
  ||';'
  ||'' -- AS "CUENTA CORRIENTE" Para el PFE y en Estructuras si se marca NO EST�N EN ESTA TABLA
  ||';'
  || '' -- AS "DIVISA CUENTA CORRIENTE" Para el PFE y en Estructuras si se NO EST�N EN ESTA TABLA
  ||';'
  ||''-- AS "CUENTA CORRIENTE" Para el PFE y en Estructuras si se marca,NO EST�N EN ESTA TABLA
  ||';'
  ||''-- AS "DIVISA CUENTA CORRIENTE 2" Para el PFE y en Estructuras si se NO EST�N EN ESTA TABLA
  -- marca, resto vac�o 
  ||';'
  || '' -- AS "CONTRATO MARCO" Para el PFE y en Estructuras. Solo est�n en SWAP NO EST�N EN ESTA TABLA
  ||';'
  || '' --AS "CCV" Vac�o para FX
  ||';'
  || RTRIM ( TO_CHAR ( OP_FWD.COST_AND_CHARGES , 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.''' ) , ',' ) --AS "COSTES Y GASTOS"
  ||';'
  || OP_FWD.CC_CURRENCY -- AS "DIVISA CyG" 
  ||';'
  || DECODE (OP.PRODUCTO,'SL','471','SF','471','SD','471','SE','471','SU','471','FW','441','FA','441','ND','440','SW','441','DW','471','SP','441') -- AS "TIPO PRODUCTO PTN" C�digo PARTEN�N
  ||';'
  || DECODE (OP.PRODUCTO,'SL','001','SF','001','SD','001','SE','001','SU','001','FW','001','FA','002','ND','040','SW','001','DW','001','SP','001') -- AS "SUBTIPO PRODUCTO PTN" C�digo PARTEN�N
  ||';'
  || MAX(NVL(DOC.ID_DOC_LPA ,'')) -- AS "ID DOC (KID)" ID_DOC_LPA si lo tenemos,sino vacio
  ||';'
  || MAX(NVL(DOC.ID_LPA ,'')) -- AS "WF ID KID" ID_LPA si lo tenemos, sino vacio
  ||';'
  ||'' -- AS "ISIN" Para FX vac�o
  ||';'
  || DECODE (OP.PRODUCTO,'SP','CURR;FXD;FXD',
                         'FW','CURR;FXD;FXD', 'FA','CURR;FXD;FXD', 
                         'SW','CURR;FXD;XSW', 'ND','CURR;FXD;FXD', 
                         'SL','CURR;OPT;BAR', 'SD','CURR;OPT;BAR', 
                         'SE','CURR;OPT;BAR', 'SU','CURR;OPT;BAR', 
                         'SF','CURR;OPT;RBT', 'DW','IRD;LN_BR;') -- AS MX_FAMILY, MX_GROUP, AS MX_TYPE
  || ';'
  || 'N' -- AS "ESTRUCTURA" NO EST�N EN ESTA TABLA
  || ';'
  || ((OP_FWD.MARGEN_OPERACION + OP_FWD.CVA) * DECODE ( SUBSTR(OP_FWD.PAR_DIVISAS,1,3), OP_FWD.DIVISA_NOMINAL_CV, OP_FWD.NOMINAL_CLIENTE_VENDE, OP_FWD.DIVISA_NOMINAL_CC ,OP_FWD.NOMINAL_CLIENTE_COMPRA))-- AS "MARKUP"  Costes y gastos totales
  ||';'
  || MF.CODMIFID --AS ACCIONM
  || ';'
  || '' -- AS CAMPID
  || ';'
  || '' -- AS C�DIGO AAFF
  || ';'
  || DECODE (OP_FWD.MIFID, 'S', 'N', 'S')  -- AS "MEDIO DE PAGO"
  ||';'
  ||  OP_FWD.CLASF_MIFID_TIT -- AS "CLASIFICACION MIFID"
  ||';'
  || DECODE(OP.CANAL,'ACELERA','OFI','INT') -- AS "CANAL"
  ||';'
  ||'' -- AS TIPO_OBJETO_CUBIERTO
  ||';'
  ||'' -- AS CONTRATO_OBJETO_CUBIERTO
  ||';'
  ||OP.PRODUCTO -- AS "CODIGO_PRODUCTO"
  || ';'
  ||'' -- AS TIPO_EVENTO
  ||';'
  ||'' -- AS CONT_PARTENON_OP_PADRE
  ||';'
  ||'' -- AS MADRE_HIJA
  ||';'
  ||'' -- AS OPERACION_MADRE
  ||';'
  ||'' -- AS ORIGEN_CONTRAPARTIDA
  ||';'
  ||'' -- AS CONTR_BASICO_VALID
  ||';'
  ||'' -- AS CONTR_BASICO_STATUS
  ||';'
  ||'' -- AS CARTA_CLASIF_IND_FIRMA
  ||';'
  ||'' -- AS CARTA_CLASIF_TIPO_FIRMA
  ||';'
  ||'' -- AS LEI_NATIONALID_VALID
  ||';'
  ||'' -- AS LEI_NATIONALID_VALUE
  ||';'
  ||'' -- AS LEI_STATUS
  ||';'
  ||'' -- AS EMIR_STATUS_REFIT
  ||';'
  ||'' -- AS DFA_ACTION
  ||';'
  ||'' -- AS FIOC_VALID
  ||';'
  ||'' -- AS FIOC_STATUS
  ||';'
  ||'' -- AS NOMINAL_MAXIMO_COBERTURA
  ||';'
  ||'' -- AS T_MIFID_TIPO_TEST
  ||';'
   ||'' -- AS T_MIFID_INDVIGENCIA
  ||';'
  ||'' -- AS T_MIFID_ESTADO_TEST
  ||';'
  ||'' -- AS T_MIFID_FECHAFIN
  ||';'
  ||'' -- AS T_MIFID_RESULTIDON
  ||';'
  ||'' -- AS T_MIFID_RESULTCONVE
  ||';'
  ||'' -- AS T_MIFID_RESULTCOBER
  ||';'
  ||'' -- AS CAMP_ORG
  ||';'
  || DECODE (OP.PRODUCTO, 'SW', RTRIM ( TO_CHAR (OP_FWD.MID_PRICE_SWAP, 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.''' ) , ',' ), RTRIM ( TO_CHAR (OP_FWD.MID_PRICE , 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.''' ) , ',' )) -- AS "MID_PRICE"
  || ';'
  || RTRIM ( TO_CHAR (OP_FWD.ADDON_AMOUNT , 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.''' ) , ',' )) -- AS "ADDON_PRICE"
  || ';'
  || OP.MIFID_ACT_TELEPHONE_CALL_RECORDED -- AS "MIFID_ACT_CALL_RECORDED"
  || ';'
  || OP.MIFID_ACT_ID -- AS "MIFID_ACT_ID"
  || '' AS DETALLE
FROM ACELER.ACE_OPERACION_FWD OP_FWD
INNER JOIN ACELER.ACE_OPERACION OP
ON OP_FWD.ID_OPERACION = OP.ID_OPERACION AND OP_FWD.ID_ENTIDAD = OP.ID_ENTIDAD
INNER JOIN ACELER.ACE_OPERACION_TITULARES TI
ON OP.ID_OPERACION      = TI.ID_OPERACION AND OP_FWD.ID_ENTIDAD = TI.ID_ENTIDAD
AND TI.TIPO_TITULARIDAD = 'T'
LEFT OUTER JOIN ACELER.ACE_MIFID MF
ON OP_FWD.ID_OPERACION = MF.ID_OPERACION AND OP_FWD.ID_ENTIDAD = MF.ID_ENTIDAD
LEFT OUTER JOIN ACELER.ACE_DOCUMENTOS DOC
ON OP_FWD.ID_OPERACION = DOC.ID_OPERACION
AND DOC.ID_TIPDOC     = 'KD' AND DOC.ID_ENTIDAD = OP_FWD.ID_ENTIDAD
LEFT OUTER JOIN ACELER.ACE_PROPUESTAS_FX PR
ON PR.ID_OPERACION = OP_FWD.ID_OPERACION AND PR.ID_ENTIDAD = OP_FWD.ID_ENTIDAD
LEFT OUTER JOIN ACELER.ACE_TEST_CLIENTE TST
ON OP.TITULAR = TST.HOSTID AND TST.FECHA_VENCIMIENTO >= SYSDATE
--WHERE FALTA DEFINIR ESTADOSSSSSSSSSSSSS
WHERE OP.ID_ESTADO IN ('FM','KE','KF','OE','OF','FF','FE') AND
TO_DATE(OP_FWD.FECHA_OPERACION,'DD/MM/YYYY') = TO_DATE(SYSDATE,'DD/MM/YYYY') 
GROUP BY OP.ID_OPERACION,OP_FWD.CONTRATO_PARTENON, OP_FWD.CONTRATO_PARTENON_SWAP, OP.PRODUCTO,OP_FWD.FECHA_OPERACION,
OP_FWD.FECHA_VENCIMIENTO,OP_FWD.DIVISA_NOMINAL_CC,DIVISA_NOMINAL_CV,
OP.NOMINAL,OP_FWD.SENTIDO,PR.ID_PROPUESTA,TST.RESUL_IDONIEDAD,
OP_FWD.SEGMENTO_TIT,TI.HOSTID,OP_FWD.CONTRAPARTIDA_TIT,
OP.IDCENT,OP.NUMGESTOR,OP.USUALTA,MF.INEXPE,MF.CDEXPEDI,MF.CODFFVV,
OP_FWD.MARGEN_OPERACION,OP_FWD.CCC,OP_FWD.CCC2,
OP_FWD.NOMINAL_CLIENTE_VENDE,OP_FWD.NOMINAL_CLIENTE_COMPRA,OP_FWD.PRECIO_TESORERIA, OP_FWD.DESTINO,OP_FWD.CVA, OP.CANAL,
OP_FWD.CLASF_MIFID_TIT, OP_FWD.MIFID, MF.CODMIFID, OP_FWD.PAR_DIVISAS, OP_FWD.CC_CURRENCY, OP_FWD.COST_AND_CHARGES, 
OP_FWD.MID_PRICE_SWAP, OP_FWD.MID_PRICE, OP_FWD.ADDON_AMOUNT,
OP.MIFID_ACT_TELEPHONE_CALL_RECORDED, OP.MIFID_ACT_ID
UNION
--DEPO SWAP
SELECT (TO_CHAR(SYSDATE, 'DD/MM/YYYY') -- AS "FECHA_PROCESO"
  ||';'
  || OP.ID_OPERACION -- AS "CODIGO_OPERACION"
  ||';'
  || 'ACE_'
  || LPAD ( OP.ID_OPERACION , 12 , '0' ) -- AS ID_OPERACION concatenado con ACE_+0 hasta 12 n�meros
  ||';'
  || '1999'
  || LPAD ( OP.ID_OPERACION , 6 , '0' ) -- AS "ID MX" 1999
  ||';'
  || '' -- AS "CONTRATO PARTENON" No se env�a a PARTEN�N
  ||';'
  || (SELECT DESCPRODUCTO FROM ACELER.ACE_PRODUCTO_OPER WHERE ID_PRODUCTO=OP.PRODUCTO AND IDIOMA = 'es') -- AS "PRODUCTO"
  ||';'
  || TO_CHAR (OP_DS.FECHA_OPERACION, 'DD/MM/YYYY HH24:MI:SS')||'.000000'-- AS "FECHA_CONTRATACION" 
  ||';'
  || TO_CHAR (OP_DS.FECHA_VENCIMIENTO,'DD/MM/YYYY') -- AS "FECHA_VENCIMIENTO"
  ||';'
  || '' -- AS "FECHA_CANCELACION" No se env�a
  ||';'
  || OP_DS.DIVISA_CLIENTE -- AS "DIVISA OPERACI�N"
  ||';'
  || (SUBSTR(OP_DS.PAR_DIVISAS,1,3) || SUBSTR(OP_DS.PAR_DIVISAS,5,3)) -- AS "PAR DE DIVISAS"
  ||';'
  || OP.NOMINAL -- AS "NOMINAL"
  ||';'
  ||'ACELERA FX' -- AS "SISTEMA ORIGEN"
  ||';'
  || 'C'--OP_DS.SENTIDO NO EST� EN FX SWAP
  ||';'
  || NVL(PR.ID_PROPUESTA,'') -- AS "ID PROPUESTA"
  ||';'
  || DECODE(NVL(PR.ID_PROPUESTA,''),'','N','S') -- AS "INDICADOR ASESORAMIENTO" No veo el indicador de asesoramiento
  ||';'
  || TST.RESUL_IDONIEDAD -- AS "RESULTADO IDONEIDAD"
  ||';'
  || 'S'-- AS "CAPITAL GARANTIZADO (S/N)" Para productos DISTINTOS A DEPOS = 'N'
  ||';'
  || '100' -- AS "% GARANTIZADO" Para productos DISTINTOS A DEPOS vac�o
  ||';'
  || OP_DS.SEGMENTO_TIT -- AS "SEGMENTO COMERCIAL" Segmento de la contrapartida
  ||';'
  || 0 -- AS "PRIMA" Vac�o para productos distintos a OPCIONES
  ||';'
  || TI.HOSTID -- AS "CONTRAPARTIDA (C�DIGO F/J)"
  ||';'
  || NVL(OP_DS.CONTRAPARTIDA_TIT,'') -- AS "C�DIGO GLCS" Si est� a NULL se deja vac�o
  ||';'
  || OP.IDCENT -- AS "OFICINA"
  ||';'
  || UPPER(NVL(OP.NUMGESTOR,OP.USUALTA)) -- AS "GESTOR/VENTAS" 
  ||';'
  ||   (select rtrim (xmlagg (xmlelement (e, TIT.HOSTID || '|')).extract ('//text()'), '|')
         from ACELER.ACE_OPERACION_TITULARES TIT
         where
         TIT.TIPO_TITULARIDAD = 'C' AND OP.ID_ENTIDAD = TIT.ID_ENTIDAD AND OP.ID_OPERACION  = TIT.ID_OPERACION 
      ) -- AS "COTITULARES"
  ||';'
  || '' -- AS "EMISOR" Vac�o
  ||';'
  || '' -- AS "NIVEL_DE_RIESGO" Para FX vac�o
  ||';'
  || NVL(MF.INEXPE,'')
  || DECODE (MF.CDEXPEDI,0,'',LPAD(TO_CHAR(MF.CDEXPEDI),15,'0'))
  -- AS "CODIGO_MIFID" Tipo ejemplo: M000000021842382 (16)
  ||';'
  || DECODE (OP_DS.SIGA,'S','0049'||LTRIM(OP_DS.ID_SIGA,'0')||'0000','') -- AS "Orden SIGA" Parece que solo est� para SWAP
  ||';'
  || NVL(MF.CODFFVV,'') -- AS "CODIGO_FFVV" C�digo del Fichero de
  -- Valores
  ||';'
  || DECODE (OP_DS.SIGA,'S',NVL(MF.CODFFVV,''),NVL(MF.CODFFVV,'')) -- AS "SIN�NIMO SIGA" Parece que solo est� para SWAP
  ||';'
  || '1' -- AS "TIPO SUBYACENTE" Para FX 1
  ||';'
  || '' -- AS "C�DIGO SUBYACENTE" Vac�o
  ||';'
  || DECODE(LENGTH(NVL(OP_DS.CCC_PARTENON_DIVISA_CLIENTE,'')),0,
            (DECODE(LENGTH(NVL(OP_DS.CCC_DIVISA_CLIENTE,'')),0,'',
                DECODE(LENGTH(OP_DS.CCC_DIVISA_CLIENTE),20,
                SUBSTR(OP_DS.CCC_DIVISA_CLIENTE,1,8) || SUBSTR(OP_DS.CCC_DIVISA_CLIENTE,11,10)),
                OP_DS.CCC_DIVISA_CLIENTE)),
             DECODE(LENGTH(OP_DS.CCC_PARTENON_DIVISA_CLIENTE),20,
                SUBSTR(OP_DS.CCC_PARTENON_DIVISA_CLIENTE,1,8) || SUBSTR(OP_DS.CCC_PARTENON_DIVISA_CLIENTE,11,10),
                OP_DS.CCC_PARTENON_DIVISA_CLIENTE)
            )          
  ||';'
  || NVL(OP_DS.DIVISA_CLIENTE,'') -- AS "DIVISA CUENTA CORRIENTE" Para el PFE y en Estructuras si se marca, resto vac�o 
  ||';'
  || DECODE(LENGTH(NVL(OP_DS.CCC_PARTENON_DIVISA_SWAP,'')),0,
          (DECODE(LENGTH(NVL(OP_DS.CCC_DIVISA_SWAP,'')),0,'',
              DECODE(LENGTH(OP_DS.CCC_DIVISA_SWAP),20,
              SUBSTR(OP_DS.CCC_DIVISA_SWAP,1,8) || SUBSTR(OP_DS.CCC_DIVISA_SWAP,11,10)),
              OP_DS.CCC_DIVISA_SWAP)),
           DECODE(LENGTH(OP_DS.CCC_PARTENON_DIVISA_SWAP),20,
              SUBSTR(OP_DS.CCC_PARTENON_DIVISA_SWAP,1,8) || SUBSTR(OP_DS.CCC_PARTENON_DIVISA_SWAP,11,10),
              OP_DS.CCC_PARTENON_DIVISA_SWAP)
          )
  ||';'
  || NVL(OP_DS.DIVISA_SWAP,'')  --AS "DIVISA CUENTA CORRIENTE 2" Para el PFE y en Estructuras si se marca, resto vac�o 
  ||';'
  || DECODE (LENGTH(OP_DS.CONTRATO_MARCO),20,SUBSTR(OP_DS.CONTRATO_MARCO,1,8)
  || SUBSTR(OP_DS.CONTRATO_MARCO,11,10),OP_DS.CONTRATO_MARCO) --  -- AS "CONTRATO MARCO" Para el PFE y en Estructuras si se
  -- marca. Solo est�n en SWAP
  ||';'
  || '' --AS "CCV" Vac�o para FX
  ||';'
  || RTRIM ( TO_CHAR ( OP_DS.MARGEN_DIVISA_CLIENTE + DECODE( OP_DS.CLIENT_FAIR_VALUE_SCOPE, 'Y', OP_DS.ADDON * OP_DS.IMPORTE_INICIO * OP_DS.MID_PRICE , '0') , 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.''' ) , ',' ) --AS "COSTES Y GASTOS"
  ||';'
  || OP_DS.DIVISA_CLIENTE -- AS "DIVISA CyG" 
  ||';'
  || (SELECT AV.VALOR FROM ACELER.ACE_VARIABLES AV WHERE AV.NOMBRE='DEPOSITO_TIPO_CONTRATO' AND ID_ENTIDAD='0049') -- AS "TIPO PRODUCTO PTN" C�digo PARTEN�N
  ||';'
  || (SELECT AV.VALOR FROM ACELER.ACE_VARIABLES AV WHERE AV.NOMBRE='DEPOSITO_SUBTIPO_CONTRATO' AND ID_ENTIDAD='0049') -- AS "SUBTIPO PRODUCTO PTN" C�digo PARTEN�N
  ||';'
  || MAX(NVL(DOC.ID_DOC_LPA ,'')) -- AS "ID DOC (KID)" ID_DOC_LPA si lo tenemos,
  -- sino vacio
  ||';'
  || MAX(NVL(DOC.ID_LPA ,'')) -- AS "WF ID KID" ID_LPA si lo tenemos, sino vacio
  ||';'
  ||'' -- AS "ISIN" Para FX vac�o
  ||';'
  || DECODE (OP.PRODUCTO,'SP','CURR;FXD;FXD',
                         'FW','CURR;FXD;FXD', 'FA','CURR;FXD;FXD', 
                         'SW','CURR;FXD;XSW', 'ND','CURR;FXD;FXD', 
                         'SL','CURR;OPT;BAR', 'SD','CURR;OPT;BAR', 
                         'SE','CURR;OPT;BAR', 'SU','CURR;OPT;BAR', 
                         'SF','CURR;OPT;RBT', 'DW','IRD;LN_BR;') -- AS MX_FAMILY, MX_GROUP, AS MX_TYPE
  ||';' 
  || 'N' -- AS "ESTRUCTURA"
  || ';'
  || OP_DS.MARGEN_DIVISA_CLIENTE -- AS "MARKUP"  Costes y gastos totales
  ||';'
  || MF.CODMIFID --AS ACCIONM
  || ';'
  || '' -- AS CAMPID
  || ';'
  || '' -- AS C�DIGO AAFF
  ||';'
  ||'N' -- AS "MEDIO DE PAGO"
  ||';'
  ||  OP_DS.CLASF_MIFID_TIT -- AS "CLASIFICACION MIFID"
  ||';'
  || DECODE(OP.CANAL,'ACELERA','OFI','INT') -- AS "CANAL"
  ||';'
  ||'' -- AS TIPO_OBJETO_CUBIERTO
  ||';'
  ||'' -- AS CONTRATO_OBJETO_CUBIERTO
  ||';'
  ||OP.PRODUCTO -- AS "CODIGO_PRODUCTO"
  || ';'
  ||'' -- AS TIPO_EVENTO
  ||';'
  ||'' -- AS CONT_PARTENON_OP_PADRE
  ||';'
  ||'' -- AS MADRE_HIJA
  ||';'
  ||'' -- AS OPERACION_MADRE
  ||';'
  ||'' -- AS ORIGEN_CONTRAPARTIDA
  ||';'
  ||'' -- AS CONTR_BASICO_VALID
  ||';'
  ||'' -- AS CONTR_BASICO_STATUS
  ||';'
  ||'' -- AS CARTA_CLASIF_IND_FIRMA
  ||';'
  ||'' -- AS CARTA_CLASIF_TIPO_FIRMA
  ||';'
  ||'' -- AS LEI_NATIONALID_VALID
  ||';'
  ||'' -- AS LEI_NATIONALID_VALUE
  ||';'
  ||'' -- AS LEI_STATUS
  ||';'
  ||'' -- AS EMIR_STATUS_REFIT
  ||';'
  ||'' -- AS DFA_ACTION
  ||';'
  ||'' -- AS FIOC_VALID
  ||';'
  ||'' -- AS FIOC_STATUS
  ||';'
  ||'' -- AS NOMINAL_MAXIMO_COBERTURA
  ||';'
  ||'' -- AS T_MIFID_TIPO_TEST
  ||';'
   ||'' -- AS T_MIFID_INDVIGENCIA
  ||';'
  ||'' -- AS T_MIFID_ESTADO_TEST
  ||';'
  ||'' -- AS T_MIFID_FECHAFIN
  ||';'
  ||'' -- AS T_MIFID_RESULTIDON
  ||';'
  ||'' -- AS T_MIFID_RESULTCONVE
  ||';'
  ||'' -- AS T_MIFID_RESULTCOBER
  ||';'
  ||'' -- AS CAMP_ORG
  ||';'
  || RTRIM ( TO_CHAR (OP_DS.MID_PRICE , 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.''' ) , ',' ) -- AS "MID_PRICE"
  || ';'
  || RTRIM ( TO_CHAR (DECODE (OP_DS.CLIENT_FAIR_VALUE_SCOPE, 'Y',  OP_DS.ADDON * OP_DS.IMPORTE_INICIO * OP_DS.MID_PRICE , '0') , 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.''' ) , ',' )) -- AS "ADDON_PRICE"
  || ';'
  || OP.MIFID_ACT_TELEPHONE_CALL_RECORDED -- AS "MIFID_ACT_CALL_RECORDED"
  || ';'
  || OP.MIFID_ACT_ID -- AS "MIFID_ACT_ID"
  || '' AS DETALLE
FROM ACELER.ACE_OPERACION_DEPO_SWAP OP_DS
INNER JOIN ACELER.ACE_OPERACION OP
ON OP_DS.ID_OPERACION = OP.ID_OPERACION AND OP_DS.ID_ENTIDAD = OP.ID_ENTIDAD
INNER JOIN ACELER.ACE_OPERACION_TITULARES TI
ON OP.ID_OPERACION      = TI.ID_OPERACION AND OP_DS.ID_ENTIDAD = TI.ID_ENTIDAD
AND TI.TIPO_TITULARIDAD = 'T'
LEFT OUTER JOIN ACELER.ACE_MIFID MF
ON OP_DS.ID_OPERACION = MF.ID_OPERACION AND OP_DS.ID_ENTIDAD = MF.ID_ENTIDAD
LEFT OUTER JOIN ACELER.ACE_DOCUMENTOS DOC
ON OP_DS.ID_OPERACION = DOC.ID_OPERACION
AND DOC.ID_TIPDOC     = 'KD' AND DOC.ID_ENTIDAD = OP_DS.ID_ENTIDAD
LEFT OUTER JOIN ACELER.ACE_PROPUESTAS_FX PR
ON PR.ID_OPERACION = OP_DS.ID_OPERACION AND PR.ID_ENTIDAD = OP_DS.ID_ENTIDAD
LEFT OUTER JOIN ACELER.ACE_TEST_CLIENTE TST
ON OP.TITULAR = TST.HOSTID AND TST.FECHA_VENCIMIENTO >= SYSDATE
--WHERE
WHERE OP.ID_ESTADO IN ('FM','FE') AND 
TO_DATE(OP_DS.FECHA_OPERACION,'DD/MM/YYYY') = TO_DATE(SYSDATE,'DD/MM/YYYY') 
GROUP BY OP.ID_OPERACION,OP_DS.CCC_PARTENON_DIVISA_CLIENTE, OP.PRODUCTO,OP_DS.FECHA_OPERACION,
OP_DS.FECHA_VENCIMIENTO,OP_DS.DIVISA_SWAP,DIVISA_CLIENTE,
OP.NOMINAL,PR.ID_PROPUESTA,TST.RESUL_IDONIEDAD,
OP_DS.SEGMENTO_TIT,TI.HOSTID,OP_DS.CONTRAPARTIDA_TIT,
OP.IDCENT,OP.NUMGESTOR,OP.USUALTA,MF.INEXPE,MF.CDEXPEDI,
OP_DS.MARGEN_OPERACION,OP_DS.CCC_DIVISA_CLIENTE,OP_DS.CCC_DIVISA_SWAP,CONTRATO_MARCO,
OP_DS.DIVISA_SWAP,OP_DS.MARGEN_DIVISA_SWAP,OP_DS.MARGEN_DIVISA_CLIENTE,OP_DS.ID_SIGA,
MF.CODFFVV,OP_DS.SIGA,CCC_PARTENON_DIVISA_SWAP, OP.CANAL, OP_DS.CLASF_MIFID_TIT, OP.ID_ENTIDAD, MF.CODMIFID,OP_DS.PAR_DIVISAS,
OP_DS.CLIENT_FAIR_VALUE_SCOPE, OP_DS.ADDON, OP_DS.IMPORTE_INICIO, OP_DS.MID_PRICE,
OP.MIFID_ACT_TELEPHONE_CALL_RECORDED, OP.MIFID_ACT_ID
UNION ALL
-- ACUMULADORES
SELECT 
(TO_CHAR(SYSDATE, 'DD/MM/YYYY') -- AS "FECHA_PROCESO"
  ||';'
  || AO.ID_OPERACION -- AS "CODIGO_OPERACION"
  ||';'
  || 'ACE_'
  || LPAD ( AO.ID_OPERACION , 12 , '0' ) -- AS ID_OPERACION concatenado con ACE_+0 hasta 12 n�meros
  ||';'
  || '1999'
  || LPAD ( AO.ID_OPERACION , 6 , '0' ) -- AS "ID MX" 1999
  ||';'
  || '' -- AS "CONTRATO PARTENON" No se env�a a PARTEN�N
  ||';'
  || 'ACUMULADOR ' || AO.TIPO_SENTIDO || ' ' || AO.TIPO_NOMINAL || ' ' || AO.TIPO_BARRERA  -- AS "PRODUCTO"
  ||';'
  || TO_CHAR (AO.FECHA_OPERACION, 'DD/MM/YYYY HH24:MI:SS')||'.000000'-- AS "FECHA_CONTRATACION" 
  ||';'
  || TO_CHAR (AO.FECHA_VENCIMIENTO,'DD/MM/YYYY') -- AS "FECHA_VENCIMIENTO"
  ||';'
  || '' -- AS "FECHA_CANCELACION" No se env�a
  ||';'
  || AO.DIVISA_NOMINAL -- AS "DIVISA OPERACI�N"
  ||';'
  || REPLACE (AO.PAR_DIVISAS ,'/','') -- AS "PAR DE DIVISAS"
  ||';'
  || AO.NOMINAL -- AS "NOMINAL"
  ||';'
  ||'ACELERA FX' -- AS "SISTEMA ORIGEN"
  ||';'
  || 'C'--OP_DS.SENTIDO NO EST� EN FX SWAP
  ||';'
  || '' -- AS "ID PROPUESTA"
  ||';'
  || 'N' -- AS "INDICADOR ASESORAMIENTO" No veo el indicador de asesoramiento
  ||';'
  || '' -- AS "RESULTADO IDONEIDAD"
  ||';'
  || 'N'-- AS "CAPITAL GARANTIZADO (S/N)" Para productos DISTINTOS A DEPOS = 'N'
  ||';'
  || '' -- AS "% GARANTIZADO" Para productos DISTINTOS A DEPOS vac�o
  ||';'
  || AC.SEGMENTO -- AS "SEGMENTO COMERCIAL" Segmento de la contrapartida
  ||';'
  || 0 -- AS "PRIMA" Vac�o para productos distintos a OPCIONES
  ||';'
  || AC.HOSTID -- AS "CONTRAPARTIDA (C�DIGO F/J)"
  ||';'
  || NVL(AC.CONTRAPARTIDA,'') -- AS "C�DIGO GLCS" Si est� a NULL se deja vac�o
  ||';'
  || AO.IDCENT -- AS "OFICINA"
  ||';'
  || UPPER(NVL(AO.NUMGESTOR,AO.USUALTA)) -- AS "GESTOR/VENTAS" 
  ||';'
  || ''  -- AS "COTITULARES"
  ||';'
  || '' -- AS "EMISOR" Vac�o
  ||';'
  || '' -- AS "NIVEL_DE_RIESGO" Para FX vac�o
  ||';'
  || NVL(AM.INEXPE,'')
  || DECODE (AM.CDEXPEDI,0,'',LPAD(TO_CHAR(AM.CDEXPEDI),15,'0'))
  -- AS "CODIGO_MIFID" Tipo ejemplo: M000000021842382 (16)
  ||';'
  || '' -- AS "Orden SIGA" 
  ||';'
  || NVL(AM.CODFFVV,'') -- AS "CODIGO_FFVV" C�digo del Fichero de
  -- Valores
  ||';'
  || '' -- AS "SIN�NIMO SIGA" Parece que solo est� para SWAP
  ||';'
  || '1' -- AS "TIPO SUBYACENTE" Para FX 1
  ||';'
  || '' -- AS "C�DIGO SUBYACENTE" Vac�o
  ||';'
  || SUBSTR(AO.CCC,1,8)||SUBSTR(AO.CCC,11)        
  ||';'
  || '' -- AS "DIVISA CUENTA CORRIENTE" Para el PFE y en Estructuras si se marca, resto vac�o 
  ||';'
  || ''
  ||';'
  || ''  --AS "DIVISA CUENTA CORRIENTE 2" Para el PFE y en Estructuras si se marca, resto vac�o 
  ||';'
  || '' --  -- AS "CONTRATO MARCO" Para el PFE y en Estructuras si se marca. Solo est�n en SWAP
  ||';'
  || '' --AS "CCV" Vac�o para FX
  ||';'
  || RTRIM(TO_CHAR(NVL(ABS(MARGEN_NETO), 0) + NVL(CVA, 0) + NVL(ABS(SALES_CREDIT), 0) + DECODE(CLIENT_FAIR_VALUE_SCOPE, 'Y', NVL(ABS(ADDON_AMOUNT), 0), 0), 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.'''), ',') --AS "COSTES Y GASTOS"
  ||';'
  || DIVISA_GRIEGA -- AS "DIVISA CyG" 
  ||';'
  || '472' -- AS "TIPO PRODUCTO PTN" C�digo PARTEN�N
  ||';'
  || '001' -- AS "SUBTIPO PRODUCTO PTN" C�digo PARTEN�N
  ||';'
  || (SELECT MAX(NVL(DOC.ID_DOC_LPA ,'')) FROM ACELER.ACE_DOCUMENTOS DOC WHERE AO.ID_OPERACION=DOC.ID_OPERACION AND DOC.ID_TIPDOC = 'KD' AND DOC.ID_ENTIDAD = AO.ID_ENTIDAD) -- AS "ID DOC (KID)" ID_DOC_LPA si lo tenemos, 
  ||';'
  || AO.ID_LPA_WORKFLOW -- AS "WF ID KID" ID_LPA si lo tenemos, sino vacio
  ||';'
  ||'' -- AS "ISIN" Para FX vac�o
  ||';'
  || 'CURR;OPT;FLEX' -- FAMILY GROUP TYPE
  ||';' 
  || 'S' -- AS "ESTRUCTURA"
  || ';'
  || MARGEN_DIVISA_GRIEGA -- AS "MARKUP"  Costes y gastos totales
  ||';'
  || AM.CODMIFID --AS ACCIONM
  || ';'
  || '' -- AS CAMPID
  || ';'
  || '' -- AS C�DIGO AAFF
  ||';'
  ||'N' -- AS "MEDIO DE PAGO"
  ||';'
  ||  AC.CLASF_MIFID -- AS "CLASIFICACION MIFID"
  ||';'
  || 'OFI' -- AS "CANAL"
  ||';'
  ||'' -- AS TIPO_OBJETO_CUBIERTO
  ||';'
  ||'' -- AS CONTRATO_OBJETO_CUBIERTO
  ||';'
  ||'AC' -- AS "CODIGO_PRODUCTO"
  || ';'
  ||'' -- AS TIPO_EVENTO
  ||';'
  ||'' -- AS CONT_PARTENON_OP_PADRE
  ||';'
  ||'' -- AS MADRE_HIJA
  ||';'
  ||'' -- AS OPERACION_MADRE
  ||';'
  ||'' -- AS ORIGEN_CONTRAPARTIDA
  ||';'
  ||'' -- AS CONTR_BASICO_VALID
  ||';'
  ||'' -- AS CONTR_BASICO_STATUS
  ||';'
  ||'' -- AS CARTA_CLASIF_IND_FIRMA
  ||';'
  ||'' -- AS CARTA_CLASIF_TIPO_FIRMA
  ||';'
  ||'' -- AS LEI_NATIONALID_VALID
  ||';'
  ||'' -- AS LEI_NATIONALID_VALUE
  ||';'
  ||'' -- AS LEI_STATUS
  ||';'
  ||'' -- AS EMIR_STATUS_REFIT
  ||';'
  ||'' -- AS DFA_ACTION
  ||';'
  ||'' -- AS FIOC_VALID
  ||';'
  ||'' -- AS FIOC_STATUS
  ||';'
  ||'' -- AS NOMINAL_MAXIMO_COBERTURA
  ||';'
  ||'' -- AS T_MIFID_TIPO_TEST
  ||';'
   ||'' -- AS T_MIFID_INDVIGENCIA
  ||';'
  ||'' -- AS T_MIFID_ESTADO_TEST
  ||';'
  ||'' -- AS T_MIFID_FECHAFIN
  ||';'
  ||'' -- AS T_MIFID_RESULTIDON
  ||';'
  ||'' -- AS T_MIFID_RESULTCONVE
  ||';'
  ||'' -- AS T_MIFID_RESULTCOBER
  ||';'
  ||'' -- AS CAMP_ORG
  ||';'
  || RTRIM(TO_CHAR(NVL(MID_PRICE , 0), 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.'''), ',') -- AS "MID_PRICE"
  || ';'
  || RTRIM(TO_CHAR(DECODE(CLIENT_FAIR_VALUE_SCOPE, 'Y', ADDON_AMOUNT, 0), 'FM99999990D99999999','NLS_NUMERIC_CHARACTERS= '',.''' ), ',')) -- AS "ADDON_PRICE"
  || ';'
  || AO.MIFID_ACT_TELEPHONE_CALL_RECORDED -- AS "MIFID_ACT_CALL_RECORDED"
  || ';'
  || AO.MIFID_ACT_ID -- AS "MIFID_ACT_ID"
  || '' AS DETALLE
FROM ACELER.ACE_ACUM_OPERACION AO
INNER JOIN ACELER.ACE_ACUM_CLIENTE AC
ON AO.ID_OPERACION = AC.ID_OPERACION 
INNER JOIN ACELER.ACE_ACUM_COTIZACION ACO
ON AO.ID_OPERACION = ACO.ID_OPERACION 
LEFT OUTER JOIN ACELER.ACE_ACUM_MIFID AM
ON AO.ID_OPERACION = AM.ID_OPERACION 
--WHERE
WHERE AO.ID_ESTADO IN ('FM','FE')  
AND TO_DATE(AO.FECHA_OPERACION,'DD/MM/YYYY') = TO_DATE(SYSDATE,'DD/MM/YYYY');


	
BEGIN    
     
	
  FOR REG IN CUR_ASES LOOP	
        BEGIN  
			
			DBMS_OUTPUT.PUT_LINE(REG.DETALLE);					
			EXCEPTION
            WHEN OTHERS THEN
				DBMS_OUTPUT.PUT_LINE('Error Producido generacion TempFX_D.dat en asesoramiento FX Diario: ' || SQLERRM);
            
        END;	
  END LOOP;  
	  
EXCEPTION
  WHEN OTHERS THEN
    BEGIN       
    	DBMS_OUTPUT.PUT_LINE('Error Producido generacion TempFX_D.dat en asesoramiento FX Diario: ' || SQLERRM);		
    EXCEPTION
      WHEN OTHERS THEN     
		DBMS_OUTPUT.PUT_LINE('Error Producido asesoramiento: ' || SQLERRM);	  
    END;
END p_asesoramiento;

BEGIN

  p_asesoramiento;
  
END; 
/

SPOOL OFF

SET VERIFY ON
SET FEEDBACK ON
SET HEAD ON
SET TERMOUT ON
SET FLUSH ON

EXIT SQL.SQLCODE

