DROP ALL OBJECTS;

CREATE SCHEMA IF NOT EXISTS ACELER;
SET SCHEMA ACELER;

  CREATE TABLE aceler.ACE_ACUM_OPERACION
   (
    	ID_ENTIDAD                  VARCHAR2(4) ,
        ID_OPERACION NUMBER ,
        ID_ESTADO                   VARCHAR2(2),
	 CONSTRAINT ACE_ACUM_OPERACION_PK PRIMARY KEY (ID_OPERACION)
   );


CREATE TABLE aceler.ACE_LPA_CONFIG_PLANT (
    ID_PLANTILLALPA VARCHAR(50),
    ID_ENTIDAD VARCHAR(10),
    LPA_ETIQUETA VARCHAR(100),
    TIPO_ORIGEN VARCHAR(50),
    VALOR_ORIGEN VARCHAR(4000),
    CONDICION VARCHAR(100),
    CONSTRAINT ACE_LPA_CONFIG_PLANT_PK PRIMARY KEY (
    ID_ENTIDAD, ID_PLANTILLALPA, LPA_ETIQUETA)
);


INSERT INTO aceler.ACE_LPA_CONFIG_PLANT (ID_PLANTILLALPA, ID_ENTIDAD, LPA_ETIQUETA, TIPO_ORIGEN, VALOR_ORIGEN, CONDICION)
VALUES ('ACUM_UDF_TODOS', '0049', 'ADDCHRG__character', 'ACE_OPERACION', 'DBMS_RANDOM.VALUE', null);



Insert into ACELER.ACE_ACUM_OPERACION
(ID_ENTIDAD,ID_OPERACION,ID_ESTADO) values ('0049','26960','EM');
Insert into ACELER.ACE_ACUM_OPERACION
(ID_ENTIDAD,ID_OPERACION,ID_ESTADO) values ('0049','27021','EM');


---------

  CREATE TABLE ACELER.ACE_ACUM_COTIZACION
   (	ID_OPERACION NUMBER NOT NULL ENABLE,
        DIVISA_GRIEGA VARCHAR2(3),
        MARGEN_NETO NUMBER,
        SALES_CREDIT NUMBER,
        ADDON_AMOUNT NUMBER,
        VALOR_MERCADO_TOTAL NUMBER,
    	 CONSTRAINT ACE_ACUM_COTIZACION_PK PRIMARY KEY (ID_OPERACION)
    );

Insert into ACELER.ACE_ACUM_COTIZACION (ID_OPERACION,SALES_CREDIT,DIVISA_GRIEGA,MARGEN_NETO,VALOR_MERCADO_TOTAL,ADDON_AMOUNT) values ('27531',null,null,null,null,'0');
Insert into ACELER.ACE_ACUM_COTIZACION (ID_OPERACION,SALES_CREDIT,DIVISA_GRIEGA,MARGEN_NETO,VALOR_MERCADO_TOTAL,ADDON_AMOUNT) values ('27515',null,null,null,null,'0');
Insert into ACELER.ACE_ACUM_COTIZACION (ID_OPERACION,SALES_CREDIT,DIVISA_GRIEGA,MARGEN_NETO,VALOR_MERCADO_TOTAL,ADDON_AMOUNT) values ('27551',null,null,null,null,'0');
Insert into ACELER.ACE_ACUM_COTIZACION (ID_OPERACION,SALES_CREDIT,DIVISA_GRIEGA,MARGEN_NETO,VALOR_MERCADO_TOTAL,ADDON_AMOUNT) values ('28002',null,null,null,null,'0');
Insert into ACELER.ACE_ACUM_COTIZACION (ID_OPERACION,SALES_CREDIT,DIVISA_GRIEGA,MARGEN_NETO,VALOR_MERCADO_TOTAL,ADDON_AMOUNT) values ('27613',null,null,null,null,'0');
Insert into ACELER.ACE_ACUM_COTIZACION (ID_OPERACION,SALES_CREDIT,DIVISA_GRIEGA,MARGEN_NETO,VALOR_MERCADO_TOTAL,ADDON_AMOUNT) values ('27637',null,null,null,null,'0');
Insert into ACELER.ACE_ACUM_COTIZACION (ID_OPERACION,SALES_CREDIT,DIVISA_GRIEGA,MARGEN_NETO,VALOR_MERCADO_TOTAL,ADDON_AMOUNT) values ('27946',null,null,null,null,'0');
Insert into ACELER.ACE_ACUM_COTIZACION (ID_OPERACION,SALES_CREDIT,DIVISA_GRIEGA,MARGEN_NETO,VALOR_MERCADO_TOTAL,ADDON_AMOUNT) values ('27938',null,null,null,null,'0');
Insert into ACELER.ACE_ACUM_COTIZACION (ID_OPERACION,SALES_CREDIT,DIVISA_GRIEGA,MARGEN_NETO,VALOR_MERCADO_TOTAL,ADDON_AMOUNT) values ('27994','1,5',null,null,null,'0');

    CREATE TABLE ACELER.ACE_ACUM_CLIENTE
   (
    ID_OPERACION NUMBER NOT NULL ENABLE,
	HOSTID VARCHAR2(10) NOT NULL ENABLE,
	CLASF_MIFID VARCHAR2(2),
	DOCUMENTO VARCHAR2(20),
	NOMBRE VARCHAR2(200),
	LEI VARCHAR2(20),
	ACUERDO_BASICO VARCHAR2(1),
	SEGMENTO VARCHAR2(2),
	CONTRAPARTIDA VARCHAR2(10),
	DOMICILIO VARCHAR2(500),
	VALIDACION_LEI VARCHAR2(1),
	LEI_VIGENTE VARCHAR2(1),
	LEI_VIGENTE_EN_PANTALLA VARCHAR2(1),
	DFA_ESTADO VARCHAR2(10),
	CARTA_CLASIFICACION_INDICADOR_FIRMADO VARCHAR2(1),
	CARTA_CLASIFICACION_TIPO_FIRMA VARCHAR2(1),
	ORIGEN_CONTRAPARTIDA_TIT VARCHAR2(1),
	CLIENT_FAIR_VALUE_SCOPE VARCHAR2(1),
	 CONSTRAINT ACE_ACUM_CLIENTE_PK PRIMARY KEY (ID_OPERACION)
   )

   Insert into ACELER.ACE_ACUM_CLIENTE (ID_OPERACION,HOSTID,CLASF_MIFID,DOCUMENTO,NOMBRE,LEI,ACUERDO_BASICO,SEGMENTO,CONTRAPARTIDA,DOMICILIO,VALIDACION_LEI,LEI_VIGENTE,LEI_VIGENTE_EN_PANTALLA,DFA_ESTADO,CARTA_CLASIFICACION_INDICADOR_FIRMADO,CARTA_CLASIFICACION_TIPO_FIRMA,ORIGEN_CONTRAPARTIDA_TIT,CLIENT_FAIR_VALUE_SCOPE) values ('26960','J000000001','MI','A40845596','RMV VALORES CON N Y ACENT','0KI513U38P254A4IFP31','Y','PB',null,null,null,null,null,null,null,null,null,null);
   Insert into ACELER.ACE_ACUM_CLIENTE (ID_OPERACION,HOSTID,CLASF_MIFID,DOCUMENTO,NOMBRE,LEI,ACUERDO_BASICO,SEGMENTO,CONTRAPARTIDA,DOMICILIO,VALIDACION_LEI,LEI_VIGENTE,LEI_VIGENTE_EN_PANTALLA,DFA_ESTADO,CARTA_CLASIFICACION_INDICADOR_FIRMADO,CARTA_CLASIFICACION_TIPO_FIRMA,ORIGEN_CONTRAPARTIDA_TIT,CLIENT_FAIR_VALUE_SCOPE) values ('27039','J000000001','MI','A40845596','RMV VALORES CON N Y ACENT','0KI513U38P254A4IFP31',null,'PB',null,null,null,null,null,null,null,null,null,null);
   Insert into ACELER.ACE_ACUM_CLIENTE (ID_OPERACION,HOSTID,CLASF_MIFID,DOCUMENTO,NOMBRE,LEI,ACUERDO_BASICO,SEGMENTO,CONTRAPARTIDA,DOMICILIO,VALIDACION_LEI,LEI_VIGENTE,LEI_VIGENTE_EN_PANTALLA,DFA_ESTADO,CARTA_CLASIFICACION_INDICADOR_FIRMADO,CARTA_CLASIFICACION_TIPO_FIRMA,ORIGEN_CONTRAPARTIDA_TIT,CLIENT_FAIR_VALUE_SCOPE) values ('27062','J000000001','MI','A40845596','RMV VALORES CON N Y ACENT','0KI513U38P254A4IFP31','Y','PB',null,null,null,null,null,null,null,null,null,null);