DROP ALL OBJECTS;

CREATE SCHEMA IF NOT EXISTS ACELER;
SET SCHEMA ACELER;

  CREATE TABLE ACE_ACUM_OPERACION
   (
    	ID_ENTIDAD VARCHAR2(4 BYTE) NOT NULL ENABLE,
        ID_OPERACION NUMBER NOT NULL ENABLE,
        ID_ESTADO VARCHAR2(2 BYTE),
        FECHA_OPERACION DATE,
        USUALTA VARCHAR2(30 BYTE),
        FECALTA TIMESTAMP (6),
        USUMODI VARCHAR2(30 BYTE),
        FECMODI TIMESTAMP (6),
        TIPO_SENTIDO VARCHAR2(50 BYTE),
        TIPO_NOMINAL VARCHAR2(50 BYTE),
        TIPO_BARRERA VARCHAR2(50 BYTE),
        DOBLE_TRAMO CHAR(1 CHAR),
        PROPUESTA_RIESGOS VARCHAR2(20 BYTE),
        CCC VARCHAR2(20 BYTE),
        CCC_PARTENON VARCHAR2(20 BYTE),
        FW_NOMINAL NUMBER,
        FW_DIVISA_NOMINAL VARCHAR2(3 BYTE),
        FW_PRECIO_ASEGURADO NUMBER,
        FW_PAR_DIVISAS VARCHAR2(7 BYTE),
        FW_FECHA_ENTREGA DATE,
        FW_FECHA_INICIO DATE,
        FW_PROPUESTA_RIESGOS VARCHAR2(20 BYTE),
        NOMINAL NUMBER,
        DIVISA_NOMINAL VARCHAR2(3 BYTE),
        PAR_DIVISAS VARCHAR2(7 BYTE),
        FECHA_VENCIMIENTO DATE,
        FECHA_ENTREGA DATE,
        FIXING_REFERENCE VARCHAR2(30 BYTE),
        DESTINO VARCHAR2(100 BYTE),
        FECHA_INICIO_PERIODO DATE,
        FECHA_VENCIMIENTO_PERIODO DATE,
        FRECUENCIA VARCHAR2(100 BYTE),
        IDCENT VARCHAR2(4 BYTE),
        NUMGESTOR VARCHAR2(20 BYTE),
        FORWARD_AMERICANO CHAR(1 CHAR),
        CANAL_INTERNO VARCHAR2(30 BYTE),
        FIJA_LIQUIDA CHAR(1 BYTE),
        PONDERADO CHAR(1 BYTE),
        ESCALONADO CHAR(1 BYTE),
        LIQUIDACION_DIFERENCIA CHAR(1 BYTE),
        AJUSTE_STRIKE VARCHAR2(30 BYTE),
        DIVISA_ENTREGA VARCHAR2(3 BYTE),
        BOLSA_PUNTOS NUMBER,
        OBSERVACION_MAX NUMBER,
        ID_COTIZACION NUMBER,
        ID_LPA_WORKFLOW NUMBER(*,0),
        PRODUCT_NAME VARCHAR2(30 BYTE),
        RENEGOCIACION CHAR(1 BYTE),
        SIN_ACUMULACION CHAR(1 BYTE),
        IMPORTE_CONSUMO NUMBER,
        IMPORTE_PROPUESTA NUMBER,
        PROPUESTA_PMP VARCHAR2(20 BYTE),
        FECHA_FIRMA_PROPUESTA_PMP DATE,
        DIVISA_PROPUESTA VARCHAR2(3 BYTE),
        MIFID_ACT_ID VARCHAR2(30 BYTE),
        MIFID_ACT_TELEPHONE_CALL_RECORDED VARCHAR2(1 BYTE),
	 CONSTRAINT ACE_ACUM_OPERACION_PK PRIMARY KEY (ID_OPERACION)
   );


CREATE TABLE ACE_LPA_CONFIG_PLANT (
    ID_PLANTILLALPA VARCHAR(50),
    ID_ENTIDAD VARCHAR(10),
    LPA_ETIQUETA VARCHAR(100),
    TIPO_ORIGEN VARCHAR(50),
    VALOR_ORIGEN VARCHAR(4000),
    CONDICION VARCHAR(100),
    CONSTRAINT ACE_LPA_CONFIG_PLANT_PK PRIMARY KEY (
    ID_ENTIDAD, ID_PLANTILLALPA, LPA_ETIQUETA)
);


INSERT INTO ACE_LPA_CONFIG_PLANT (ID_PLANTILLALPA, ID_ENTIDAD, LPA_ETIQUETA, TIPO_ORIGEN, VALOR_ORIGEN, CONDICION)
VALUES ('ACUM_UDF_TODOS', '0049', 'ADDCHRG__character', 'ACE_OPERACION', 'DBMS_RANDOM.VALUE', null);





Insert into ACE_ACUM_OPERACION (ID_ENTIDAD,ID_OPERACION,ID_ESTADO,FECHA_OPERACION,USUALTA,FECALTA,USUMODI,FECMODI,TIPO_SENTIDO,TIPO_NOMINAL,TIPO_BARRERA,DOBLE_TRAMO,PROPUESTA_RIESGOS,CCC,CCC_PARTENON,FW_NOMINAL,FW_DIVISA_NOMINAL,FW_PRECIO_ASEGURADO,FW_PAR_DIVISAS,FW_FECHA_ENTREGA,FW_FECHA_INICIO,FW_PROPUESTA_RIESGOS,NOMINAL,DIVISA_NOMINAL,PAR_DIVISAS,FECHA_VENCIMIENTO,FECHA_ENTREGA,FIXING_REFERENCE,DESTINO,FECHA_INICIO_PERIODO,FECHA_VENCIMIENTO_PERIODO,FRECUENCIA,IDCENT,NUMGESTOR,FORWARD_AMERICANO,CANAL_INTERNO,FIJA_LIQUIDA,PONDERADO,ESCALONADO,LIQUIDACION_DIFERENCIA,AJUSTE_STRIKE,DIVISA_ENTREGA,BOLSA_PUNTOS,OBSERVACION_MAX,ID_COTIZACION,ID_LPA_WORKFLOW,PRODUCT_NAME,RENEGOCIACION,SIN_ACUMULACION,IMPORTE_CONSUMO,IMPORTE_PROPUESTA,PROPUESTA_PMP,FECHA_FIRMA_PROPUESTA_PMP,DIVISA_PROPUESTA,MIFID_ACT_ID,MIFID_ACT_TELEPHONE_CALL_RECORDED) values ('0049','26960','EM',to_date('25/03/20','DD/MM/RR'),null,null,null,null,'IMPORT','SIMPLE','RESURRECTING','Y','22222222222222222','33333333333333333333',null,'100','EUR','1','EUR/AED',null,null,'33333333333333333',null,'EUR',null,null,null,null,'2440',null,null,'DAILY','0002','n11111',null,'ACELERA',null,null,null,null,null,null,null,null,null,null,null,'N',null,null,null,null,null,null,null,null);
Insert into ACE_ACUM_OPERACION (ID_ENTIDAD,ID_OPERACION,ID_ESTADO,FECHA_OPERACION,USUALTA,FECALTA,USUMODI,FECMODI,TIPO_SENTIDO,TIPO_NOMINAL,TIPO_BARRERA,DOBLE_TRAMO,PROPUESTA_RIESGOS,CCC,CCC_PARTENON,FW_NOMINAL,FW_DIVISA_NOMINAL,FW_PRECIO_ASEGURADO,FW_PAR_DIVISAS,FW_FECHA_ENTREGA,FW_FECHA_INICIO,FW_PROPUESTA_RIESGOS,NOMINAL,DIVISA_NOMINAL,PAR_DIVISAS,FECHA_VENCIMIENTO,FECHA_ENTREGA,FIXING_REFERENCE,DESTINO,FECHA_INICIO_PERIODO,FECHA_VENCIMIENTO_PERIODO,FRECUENCIA,IDCENT,NUMGESTOR,FORWARD_AMERICANO,CANAL_INTERNO,FIJA_LIQUIDA,PONDERADO,ESCALONADO,LIQUIDACION_DIFERENCIA,AJUSTE_STRIKE,DIVISA_ENTREGA,BOLSA_PUNTOS,OBSERVACION_MAX,ID_COTIZACION,ID_LPA_WORKFLOW,PRODUCT_NAME,RENEGOCIACION,SIN_ACUMULACION,IMPORTE_CONSUMO,IMPORTE_PROPUESTA,PROPUESTA_PMP,FECHA_FIRMA_PROPUESTA_PMP,DIVISA_PROPUESTA,MIFID_ACT_ID,MIFID_ACT_TELEPHONE_CALL_RECORDED) values ('0049','27021','EM',to_date('27/03/20','DD/MM/RR'),null,null,null,null,'IMPORT','DOBLE','RESURRECTING','Y','12121212121211212','23432423434343',null,'1000','EUR','1,2','CAD/DKK',to_date('25/03/20','DD/MM/RR'),null,'66666666121212121','1000','EUR','AUD/SGD',to_date('19/03/20','DD/MM/RR'),to_date('26/03/20','DD/MM/RR'),'EUR/CLP OB/BFIX 14.0','2440',to_date('28/03/20','DD/MM/RR'),to_date('03/04/20','DD/MM/RR'),'DAILY','1415','1212','Y','ACELERA',null,null,null,null,null,null,null,null,null,null,null,'N',null,null,null,null,null,null,null,null);
Insert into ACE_ACUM_OPERACION (ID_ENTIDAD,ID_OPERACION,ID_ESTADO,FECHA_OPERACION,USUALTA,FECALTA,USUMODI,FECMODI,TIPO_SENTIDO,TIPO_NOMINAL,TIPO_BARRERA,DOBLE_TRAMO,PROPUESTA_RIESGOS,CCC,CCC_PARTENON,FW_NOMINAL,FW_DIVISA_NOMINAL,FW_PRECIO_ASEGURADO,FW_PAR_DIVISAS,FW_FECHA_ENTREGA,FW_FECHA_INICIO,FW_PROPUESTA_RIESGOS,NOMINAL,DIVISA_NOMINAL,PAR_DIVISAS,FECHA_VENCIMIENTO,FECHA_ENTREGA,FIXING_REFERENCE,DESTINO,FECHA_INICIO_PERIODO,FECHA_VENCIMIENTO_PERIODO,FRECUENCIA,IDCENT,NUMGESTOR,FORWARD_AMERICANO,CANAL_INTERNO,FIJA_LIQUIDA,PONDERADO,ESCALONADO,LIQUIDACION_DIFERENCIA,AJUSTE_STRIKE,DIVISA_ENTREGA,BOLSA_PUNTOS,OBSERVACION_MAX,ID_COTIZACION,ID_LPA_WORKFLOW,PRODUCT_NAME,RENEGOCIACION,SIN_ACUMULACION,IMPORTE_CONSUMO,IMPORTE_PROPUESTA,PROPUESTA_PMP,FECHA_FIRMA_PROPUESTA_PMP,DIVISA_PROPUESTA,MIFID_ACT_ID,MIFID_ACT_TELEPHONE_CALL_RECORDED) values ('0049','27039','EM',to_date('27/03/20','DD/MM/RR'),null,null,null,null,'EXPORT','DOBLE','RESURRECTING','N',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'2440',to_date('24/03/20','DD/MM/RR'),to_date('27/03/20','DD/MM/RR'),'DAILY','1415','N11111','N','ACELERA',null,null,null,null,null,null,null,null,null,null,null,'N',null,null,null,null,null,null,null,null);
Insert into ACE_ACUM_OPERACION (ID_ENTIDAD,ID_OPERACION,ID_ESTADO,FECHA_OPERACION,USUALTA,FECALTA,USUMODI,FECMODI,TIPO_SENTIDO,TIPO_NOMINAL,TIPO_BARRERA,DOBLE_TRAMO,PROPUESTA_RIESGOS,CCC,CCC_PARTENON,FW_NOMINAL,FW_DIVISA_NOMINAL,FW_PRECIO_ASEGURADO,FW_PAR_DIVISAS,FW_FECHA_ENTREGA,FW_FECHA_INICIO,FW_PROPUESTA_RIESGOS,NOMINAL,DIVISA_NOMINAL,PAR_DIVISAS,FECHA_VENCIMIENTO,FECHA_ENTREGA,FIXING_REFERENCE,DESTINO,FECHA_INICIO_PERIODO,FECHA_VENCIMIENTO_PERIODO,FRECUENCIA,IDCENT,NUMGESTOR,FORWARD_AMERICANO,CANAL_INTERNO,FIJA_LIQUIDA,PONDERADO,ESCALONADO,LIQUIDACION_DIFERENCIA,AJUSTE_STRIKE,DIVISA_ENTREGA,BOLSA_PUNTOS,OBSERVACION_MAX,ID_COTIZACION,ID_LPA_WORKFLOW,PRODUCT_NAME,RENEGOCIACION,SIN_ACUMULACION,IMPORTE_CONSUMO,IMPORTE_PROPUESTA,PROPUESTA_PMP,FECHA_FIRMA_PROPUESTA_PMP,DIVISA_PROPUESTA,MIFID_ACT_ID,MIFID_ACT_TELEPHONE_CALL_RECORDED) values ('0049','27062','EM',to_date('30/03/20','DD/MM/RR'),null,null,null,null,'IMPORT','SIMPLE','RESURRECTING','N','11111111111111111','22222222222222222222',null,null,null,null,null,null,null,null,'1234','ARS','AUD/CHF',to_date('31/03/20','DD/MM/RR'),to_date('31/03/20','DD/MM/RR'),'Archiving2','2440',to_date('31/03/20','DD/MM/RR'),to_date('01/04/20','DD/MM/RR'),'DAILY','0001','n11111','N','ACELERA',null,null,null,null,null,null,null,null,null,null,null,'N',null,null,null,null,null,null,null,null);
Insert into ACE_ACUM_OPERACION (ID_ENTIDAD,ID_OPERACION,ID_ESTADO,FECHA_OPERACION,USUALTA,FECALTA,USUMODI,FECMODI,TIPO_SENTIDO,TIPO_NOMINAL,TIPO_BARRERA,DOBLE_TRAMO,PROPUESTA_RIESGOS,CCC,CCC_PARTENON,FW_NOMINAL,FW_DIVISA_NOMINAL,FW_PRECIO_ASEGURADO,FW_PAR_DIVISAS,FW_FECHA_ENTREGA,FW_FECHA_INICIO,FW_PROPUESTA_RIESGOS,NOMINAL,DIVISA_NOMINAL,PAR_DIVISAS,FECHA_VENCIMIENTO,FECHA_ENTREGA,FIXING_REFERENCE,DESTINO,FECHA_INICIO_PERIODO,FECHA_VENCIMIENTO_PERIODO,FRECUENCIA,IDCENT,NUMGESTOR,FORWARD_AMERICANO,CANAL_INTERNO,FIJA_LIQUIDA,PONDERADO,ESCALONADO,LIQUIDACION_DIFERENCIA,AJUSTE_STRIKE,DIVISA_ENTREGA,BOLSA_PUNTOS,OBSERVACION_MAX,ID_COTIZACION,ID_LPA_WORKFLOW,PRODUCT_NAME,RENEGOCIACION,SIN_ACUMULACION,IMPORTE_CONSUMO,IMPORTE_PROPUESTA,PROPUESTA_PMP,FECHA_FIRMA_PROPUESTA_PMP,DIVISA_PROPUESTA,MIFID_ACT_ID,MIFID_ACT_TELEPHONE_CALL_RECORDED) values ('0049','27157','XX',to_date('02/04/20','DD/MM/RR'),null,null,null,null,'IMPORT','SIMPLE','RESURRECTING','Y','11111111111111111','22222222222222222222',null,'120','EUR','1,2','EUR/USD',to_date('04/04/20','DD/MM/RR'),to_date('03/04/20','DD/MM/RR'),'33333333333333333','123','EUR','EUR/USD',to_date('07/04/20','DD/MM/RR'),to_date('08/04/20','DD/MM/RR'),'Archiving2','2440',to_date('04/04/20','DD/MM/RR'),to_date('08/04/20','DD/MM/RR'),'DAILY','0009','n11111','Y','ACELERA',null,null,null,null,null,null,null,null,null,null,null,'N',null,null,null,null,null,null,null,null);
